//
// ModelCharacter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ModelCharacter: Codable {

    public var id: Int?
    public var name: String?
    public var status: String?
    public var species: String?
    public var type: String?
    public var gender: String?
    public var origin: Place?
    public var location: Place?
    public var image: String?
    public var episode: [String]?
    public var url: String?
    public var created: String?

    public init(id: Int?, name: String?, status: String?, species: String?, type: String?, gender: String?, origin: Place?, location: Place?, image: String?, episode: [String]?, url: String?, created: String?) {
        self.id = id
        self.name = name
        self.status = status
        self.species = species
        self.type = type
        self.gender = gender
        self.origin = origin
        self.location = location
        self.image = image
        self.episode = episode
        self.url = url
        self.created = created
    }


}

